### ISSUE TITLE
TypeError: can't access property "reload", this.multiClamp is undefined

### ISSUE THREAD

**Issue by szaleq** [jackyr/react-multi-clamp#12]
This error can happen if the `componentDidUpdate` method gets called too soon because the `MultiClamp` instance is not created directly inside `componentDidMount` but in the callback to `setState`, which is asynchronous. So if props change really quickly (which can happen and actually happened in my app) the code from [componentDidUpdate](https://github.com/jackyr/react-multi-clamp/blob/master/src/MultiClamp.jsx#L76) gets executed before the [MultiClamp instance was created](https://github.com/jackyr/react-multi-clamp/blob/master/src/MultiClamp.jsx#L60). 

There are two possible solutions to this:
1. Instantiate the `MultiClamp` class directly inside the `componentDidUpdate` instead of in the `setState` callback (I don't see any reason to do it in the callback, honestly)
2. Add a condition in `componentDidUpdate` to make sure that the instance exists before calling its method.

**Comment by jackyr** [comment]
Fixed in v2.0.6. Thanks for feedback!
