### ISSUE TITLE
How to detect when the ellipsis is applied?

### ISSUE THREAD

**Issue by giancarlosisasi** [jackyr/react-multi-clamp#2]
First, thanks for build this awesome react package!
I want to show a tooltip with the full text only if the ellipsis is applied, how can I detect that?

**Comment by jackyr** [comment]
@GiancarlosIO  

Hi, I added two callback functions in version 1.1.0: onClampStart({ needClamp }) and onClampEnd({ didClamp }). You can use the param needClamp or didClamp to detect whether the ellipsis is applied.

Here's an example([demo page](https://jackyr.github.io/react-multi-clamp/site/)) I wrote for your referrence: https://github.com/jackyr/react-multi-clamp/blob/master/example/MultiClampWithTooltip.jsx

Welcome feedback.

**Comment by giancarlosisasi** [comment]
@jackyr thanks!!!
It works like a charm!
