### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wongsitu** [jackyr/react-multi-clamp#4]
I've been using this library trying to render table entries and this problem pops up. I have no idea what's going on. Pls help.

![image](https://user-images.githubusercontent.com/21975542/70485396-d6509300-1abc-11ea-88f0-e3efebd07007.png)
![image](https://user-images.githubusercontent.com/21975542/70485426-ec5e5380-1abc-11ea-90e8-71345d8e39d0.png)

**Comment by jackyr** [comment]
Can't figure out the problem from the screenshot. Could u provide a simple error demo in [codesandbox](https://codesandbox.io/s/flamboyant-minsky-bu63j)?

**Comment by alobe** [comment]
https://codesandbox.io/s/tender-tereshkova-ucgi2?file=/src/App.js
在函数组件短时间有多个依赖变量造成多次渲染，就可能造成这个问题，看着像是计算过于频繁了，可能需要防抖节流下，例子里的报错虽然不太一致，但是组件写法稍微改下就出现了

**Comment by jackyr** [comment]
@alobe 你的这个问题是因为在内容区域放入了元素`<span>{text}</span>`，引发了一些错误

![image](https://user-images.githubusercontent.com/4645227/93197632-77702680-f77e-11ea-8323-16fd1f3f655d.png)

注意**被裁切的内容必须是纯文本**`{text}`，因为元素的裁切很难支持（底层需要解析html标签）

上述例子中，将span元素去除即可正常工作：https://codesandbox.io/s/frosty-lalande-tv0lg?file=/src/App.js

**Comment by alobe** [comment]
@jackyr 好的，感谢，因为我这边试了下span好像能包进去，就这么弄了
