### ISSUE TITLE
the react-multi-clamp@2.0.1 donot work when ellipsis is a reactelement

### ISSUE THREAD

**Issue by heizhishi** [jackyr/react-multi-clamp#5]
in your example:code 50line
```
<MultiClamp 
          clamp={2} 
          ellipsis={<a style={{ color: 'blue', marginLeft: '5px', cursor: 'pointer' }} onClick={this.handleClick}>more>></a>} 
          splitByWords 
          ref={ref => this.instance2 = ref}>
          {text1}
</MultiClamp>
```

when you change the clamp from 2 to 10 , then the bug come here
![image](https://user-images.githubusercontent.com/20233736/84745879-c83d7b00-afe7-11ea-850e-f642580c0043.png)

thank your  for you work at last.

**Comment by heizhishi** [comment]
i  find the reason.in your multi-clamp.js(method:doNotNeedToClamp donot hide the ellipsis when ellipsis is a reactdom ).i suggest modify the mothod like that
```

      function doNotNeedToClamp(isForcePrevent) {
        
        if (!isForcePrevent) self.option.onClampStart.call(self, {
          needClamp: false
        });
        self.option.onClampEnd.call(self, {
          didClamp: false
        });
         
        self.element.appendChild(self.ellipsis );
        self.element.removeChild(self.ellipsis )
      }
    },
```

thank you

**Comment by jackyr** [comment]
@heizhishi Thanks a lot. It's definitely a bug of `react-multi-clamp`, but not `multi-clamp`. 
I won't modify `multi-clamp.js` in case of unexpected trouble. This bug now fixed in `react-multi-clamp@2.0.2`.

**Comment by ZhengXingchi** [comment]
@jackyr  oh, it would be better to remove   ellipsis  in your plan.I will close the issue. thank you.

**Comment by heizhishi** [comment]
@jackyr oh, it would be better to remove ellipsis in your plan.I will close the issue. thank you.
