### ISSUE TITLE
Uncaught TypeError: Cannot read property 'reload' of undefined

### ISSUE THREAD

**Issue by zamlahani** [jackyr/react-multi-clamp#6]
`Uncaught TypeError: Cannot read property 'reload' of undefined`

It happens when I navigate from another react-router page to a page that has `MultiClamp` component(s)

sometimes the error is

`TypeError: this.multiClamp is undefined`

**Comment by jackyr** [comment]
@zamlahani 
I guess you are clamping a react element, like: 
```jsx
<MultiClamp>
  <div>{longText}</div>
</MultiClamp>
````
The `react-multi-clamp` dosen't support that. **Just clamp pure text**:
```jsx
<div>
  <MultiClamp>
    {longText}
  </MultiClamp>
</div>
````

**Comment by zamlahani** [comment]
ah I see... It works! thank you so much, your library is cool!

**Comment by jackyr** [comment]
My pleasure :)
