### ISSUE TITLE
typescript error checking

### ISSUE THREAD

**Issue by achmadk** [jackyr/react-multi-clamp#9]
Hello @jackyr . I am using `react-multi-clamp` into my web app. I am using typescript programming language. Unfortunately, when using `tsc`, I got this error:

```sh
node_modules/react-multi-clamp/index.d.ts:31:11 - error TS2304: Cannot find name 'Ref'.

31     ref?: Ref<MultiClampHTMLDivElement>;
             ~~~

node_modules/react-multi-clamp/index.d.ts:34:3 - error TS1038: A 'declare' modifier cannot be used in an already ambient context.

34   declare const Clamp: React.FC<ClampProps>;
```

if you don't mind, you can view [revision for this issue](https://github.com/jackyr/react-multi-clamp/compare/master...achmadk:fix-typescript-definition)

**Comment by jackyr** [comment]
Thanks for feedback. This error now fixed in react-multi-clamp@2.0.4.
